### ISSUE TITLE
Ubuntu 12.04 不能用

### ISSUE THREAD

**Issue by stevenfrog** [LiuLang/bcloud-packages#123]
已经按照步骤安装所有dependencies

5.更新python3-keyring到v4.0, ubuntu系统里的是v0.7: $ sudo pip3 install --upgrade keyring
Successfully installed keyring-5.0

注意, 现在keyring 是5.0了

但是还是不能打开, 我从console中试了一下:

stevenfrog@frog-Z87P:~$ bcloud-gui
Traceback (most recent call last):
  File "/usr/bin/bcloud-gui", line 11, in <module>
    from bcloud.App import App
ImportError: No module named 'bcloud'

**Comment by LiuLang** [comment]
你用哪种方法安装的bcloud? 错误提示 无法找到bcloud模块. 请使用deb包直接安装.

**Comment by stevenfrog** [comment]
直接deb安装啊, bcloud_3.6.1-1_all.deb, 哪里能看错误日志?

**Comment by LiuLang** [comment]
终端里面提示的很清楚了, 找不到bcloud这个python模块. 你看一下/usr/lib/python3/dist-packages/bcloud  个目录是否存在

**Comment by stevenfrog** [comment]
(py34) stevenfrog@frog-Z87P:~$ bcloud-gui 
Traceback (most recent call last):
  File "/usr/bin/bcloud-gui", line 11, in <module>
    from bcloud.App import App
ImportError: No module named 'bcloud'
(py34) stevenfrog@frog-Z87P:~$ ls /usr/lib/python3/dist-packages/bcloud/
App.py              const.py         FolderBrowserDialog.py  log.py                PropertiesDialog.py  Uploader.py
auth.py             decoder.py       gutil.py                MimeProvider.py       RenameDialog.py      UploadPage.py
BTBrowserDialog.py  Downloader.py    hasher.py               net.py                RequestCookie.py     util.py
CategoryPage.py     DownloadPage.py  HomePage.py             NewFolderDialog.py    SharePage.py         VCodeDialog.py
CloudPage.py        encoder.py       IconWindow.py           pcs.py                SigninDialog.py      Widgets.py
Config.py           ErrorMsg.py      __init__.py             PreferencesDialog.py  TrashPage.py
(py34) stevenfrog@frog-Z87P:~$

**Comment by stevenfrog** [comment]
找到问题了, 是我的env python3找不到, 所以出错了.
