### ISSUE TITLE
Does not support SMS/Email verification

### ISSUE THREAD

**Issue by zyy34472** [LiuLang/bcloud-packages#125]
在输入验证码后，就会出现：不支持sms/emali认证。
系统是Ubuntu 14.04 64位

**Comment by LiuLang** [comment]
目前不支持这类二次验证.
可以在 passport.baidu.com 里面查看当前帐号是否开启了二步验证.

**Comment by zyy34472** [comment]
多谢LiuLiang大牛，问题已解决
