### ISSUE TITLE
卡在get bdstoken下不去了

### ISSUE THREAD

**Issue by mryux** [LiuLang/bcloud-packages#134]
我使用的是archlinux，用hotmail的账户登录百度云就卡在"get bdstoken"这里下不去了，但是我用gmail的账户就可以。
使用的是最新版本的bcloud，不过之前的版本就有这个问题。

**Comment by mryux** [comment]
看上去像是本地cache有问题，不过不知道cache在哪里，也没法清除试试。
不知道猜的对不对，不过很感谢大神的辛勤劳动，让我们有这么好用的工具。

**Comment by LiuLang** [comment]
On 05/16/2015 08:38 PM, Yu Xiang wrote:
> 看上去像是本地cache有问题，不过不知道cache在哪里，也没法清除试试。
> 不知道猜的对不对，不过很感谢大神的辛勤劳动，让我们有这么好用的工具。
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/bcloud-packages/issues/134#issuecomment-102623511
>
本地缓存位于~/.cache/bcloud/目录.

**Comment by mryux** [comment]
清除cache以后问题解决，好象是auth.json的问题。谢谢！
