### ISSUE TITLE
输入验证码通过不了

### ISSUE THREAD

**Issue by cangyan** [LiuLang/bcloud-packages#141]
今早开始，一直通过不了验证。

**Comment by bash-horatio** [comment]
验证码填写正确，但是报错“unknown error”， 难道百度那边的接口有变动？

**Comment by cangyan** [comment]
我的问题解决了，手机绑定了百度云，安全评测到90分以上，又特么可以用了。
大部分账号异常都归“unknown error”吧。
我看了接口，没有变动，也没看见更新的新闻。

**Comment by bash-horatio** [comment]
了解，谢谢！

**Comment by bash-horatio** [comment]
感觉就是百度刷了流氓，想获取用户的手机号。我绑定完手机，啥都没做，就行了

**Comment by cangyan** [comment]
是啊，相当流氓。要不是dropbox国内不能用，早废了百度云。狗屎一样的功能。前天晚上不行，改的资料没同步上传，昨天绑了手机，直接点开网盘的文件，把本地新的文件给覆盖了，日了狗了。坑死爹。
