### ISSUE TITLE
openSUSE的OBS源的Bcloud问题

### ISSUE THREAD

**Issue by mcjoeng** [LiuLang/bcloud-packages#154]
安装OBS源的Bcloud会把一大堆KDE的libs都安装，但是不是所有openSUSE使用者都用KDE桌面，而且SUSE的商业版桌面SLES已经不支持KDE了。我用的gnome shell桌面， 安装bcloud的时候，几百M的kde libs都被看作依赖了，吓我一跳。。。

**Comment by LiuLang** [comment]
On 10/02/2015 11:19 AM, 棱镜 wrote:
> 安装OBS源的Bcloud会把一大堆KDE的libs都安装，但是不是所有openSUSE使用者都用KDE桌面，而且SUSE的商业版桌面SLES已经不支持KDE了。我用的gnome shell桌面， 安装bcloud的时候，几百M的kde libs都被看作依赖了，吓我一跳。。。
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/bcloud-packages/issues/154
>

这个可能是他打包时写的软件包依赖关系有问题. bcloud本身并不会依赖gnome或 
者kde自己的组件.

如果愿意折腾折腾的话, 可以根据 https://github.com/liulang/bcloud- 
packages 里面列出的依赖关系, 自己学着打一下包 ;-(
