### ISSUE TITLE
bcloud更新后在ubuntu14.04上打不开

### ISSUE THREAD

**Issue by momoxionger** [LiuLang/bcloud-packages#155]
无论是dash还是app下面还是终端都打不开，我确定已经装了你所要求的所有环境
![2015-10-04 18 57 41](https://cloud.githubusercontent.com/assets/11884106/10267524/47159010-6aca-11e5-9325-76a3d06e2c28.png)
你先帮我看看是什么问题，可能是我动过python环境，我去重装试试先

**Comment by LiuLang** [comment]
On 10/04/2015 07:07 PM, lan wrote:
> 无论是dash还是app下面还是终端都打不开，我确定已经装了你所要求的所有环境
> ![2015-10-04 18 57 41](https://cloud.githubusercontent.com/assets/11884106/10267524/47159010-6aca-11e5-9325-76a3d06e2c28.png)
> 你先帮我看看是什么问题，可能是我动过python环境，我去重装试试先
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/bcloud-packages/issues/155
>

这个估计是你的PYTHONPATH 环境变量被重写了.
正常情况下, sys.path 里面是会包含 /usr/lib/python3/dist-packages/ 这个目 
录的. 当然, 我也测试了, 全新安装的ubuntu 14.04里, 确实是有这个路径的. 因 
为debian的第三方python3的包都会放到 /usr/lib/python3/dist-packages/ 这个 
目录里的.
