### ISSUE TITLE
failed to get bdstoken   debian

### ISSUE THREAD

**Issue by ivo-wang** [LiuLang/bcloud-packages#162]
重试了好多次罗不管用，baidu显示已经登录了，查看了几乎所有的issues没有解决。
系统debian sid

百度的登录历史
以下为您最近20次登录记录，若存在异常情况，请在核实后尽快修改密码
时间	地点	IP	浏览器	登录方式	设备
今天					
21:17	天津	218.68.*.*	Firefox 31.0	用户名登录	电脑 (Linux)
21:16	天津	218.68.*.*	Firefox 31.0	用户名登录	电脑 (Linux)
21:12	天津	218.68.*.*	Firefox 31.0	用户名登录	电脑 (Linux)
21:08	天津	218.68.*.*	Firefox 31.0	用户名登录	电脑 (Linux)
21:00	天津	218.68.*.*	Firefox 31.0	用户名登录	电脑 (Linux)

.configure/bcloud/bcloud.log
2015-12-16 21:12:42,936 ERROR SigninDialog.on_get_bdstoken: , None
2015-12-16 21:16:34,440 ERROR SigninDialog.on_post_login: (7, None), None
2015-12-16 21:16:46,570 ERROR SigninDialog.on_get_bdstoken: , None
2015-12-16 21:16:53,263 ERROR SigninDialog.on_get_bdstoken: , None

能清楚是/usr/lib/python3/dist-packages/bcloud/auth.py   出了问题但是不知道该怎么改

**Comment by jtliaw** [comment]
有大神更新了！
sudo gedit /usr/lib/python3/dist-packages/bcloud/auth.py

找到：
bds_re = re.compile('BDSTOKEN\s*=\s*"([^"]+)"')

换成：
bds_re = re.compile('"bdstoken"\s*:\s*"([^"]+)"', re.IGNORECASE)

https://github.com/LiuLang/bcloud/pull/214/files

**Comment by fengchenxiujisd** [comment]
我的改完还是不行..

**Comment by jtliaw** [comment]
不可能啊！每个人都可以啊！别复制我写的，到链接链内的复制！

**Comment by fengchenxiujisd** [comment]
确实 原来是tab缩进问题... 
把 re.IGNORECASE前面的空格删了改为tab 修复python inconsistent use of tabs and spaces in indentation

**Comment by laichiaheng** [comment]
話說現在就算能登入，下載還是狂錯誤...幾乎不能下載的程度，這 bcloud 真的已經被拋棄了...
